<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{51aa1b40-096d-43e9-9fc4-b34a7ff3d064}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//cmt 1
	bTest_1 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// --- Version 1 --- 
// Program 1
// -----------------]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>