<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{51aa1b40-096d-43e9-9fc4-b34a7ff3d064}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//cmt 1
	bTest_1 : BOOL;
	
	//cmt 2
	bTest_2 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// --- Version 1 --- 
// Program 1
// -----------------


// --- Version 2 --- 
// Program 2
// -----------------


// --- Version 3 --- 
// Khang
// -----------------]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="16" Count="2" />
      <LineId Id="27" Count="3" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>